{"name": "test_login[datainfo1-baseinfo0-caseinfo0]", "status": "broken", "statusDetails": {"message": "RecursionError: maximum recursion depth exceeded while calling a Python object", "trace": "self = <testcases.test_login.TestLogin object at 0x000000000483B8E0>\nbaseinfo = {'base': {'base_url': 'https://api.wy56.com/test/wms-api', 'index_url': 'https://www.wy56.com/test/h5/keyi-wms/', 'pre...: 'Bearer'}, 'log': {'log_fomat': '[%(asctime)s] %(filename)s->%(funcname)s', 'log_level': 'info', 'log_name': 'log_'}}\ncaseinfo = {'name': '$csv{name}', 'parameters': {'name-login-assert_str': 'test_login.csv'}, 'requests': {'data': {'data': {'data.../login'}, 'method': 'post', 'url': '/system/login'}, 'validate': {'assert_str': '$csv{assert_str}', 'equals': 2000000}}\ndatainfo = {'assert_str': '4030000', 'loginType': '1', 'name': '登录测试', 'password': '123456', ...}\n\n    @allure.feature('登录测试')\n    @pytest.mark.parametrize('caseinfo', YamlUtil().read_test_yamlfile('test_login.yaml'))\n    @pytest.mark.parametrize('baseinfo', YamlUtil().read_yamlfile('config.yaml'))\n    @pytest.mark.parametrize('datainfo', DataUtil().csv_read('test_login.csv'))\n    def test_login(self, baseinfo, caseinfo, datainfo):\n        method = caseinfo[\"requests\"][\"method\"]\n        post_type = \"form\"\n        last_url = baseinfo[\"base\"][\"base_url\"] + caseinfo[\"requests\"][\"url\"]\n        # for data_key in caseinfo[\"requests\"][\"data\"].keys():\n        #     for i in datainfo.keys():\n        #         if data_key == i:\n        #             caseinfo[\"requests\"][\"data\"][data_key] = datainfo[i]\n>       caseinfo[\"requests\"][\"data\"] = DictUtil().dict_handle(caseinfo[\"requests\"],datainfo)\n\ntestcases\\test_login.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\dict_util.py:11: in dict_handle\n    self.dict_handle(dic1[i],dic2)\ncommon\\dict_util.py:11: in dict_handle\n    self.dict_handle(dic1[i],dic2)\nE   RecursionError: maximum recursion depth exceeded while calling a Python object\n!!! Recursion detected (same locals & position)"}, "parameters": [{"name": "datainfo", "value": "{'name': '登录测试', 'story': '错误账号登录', 'loginType': '1', 'userName': '上海管理1', 'password': '123456', 'assert_str': '4030000'}"}, {"name": "baseinfo", "value": "{'base': {'index_url': 'https://www.wy56.com/test/h5/keyi-wms/', 'base_url': 'https://api.wy56.com/test/wms-api', 'pre_auth': 'Bearer'}, 'log': {'log_name': 'log_', 'log_level': 'info', 'log_fomat': '[%(asctime)s] %(filename)s->%(funcname)s'}}"}, {"name": "caseinfo", "value": "{'name': '$csv{name}', 'parameters': {'name-login-assert_str': 'test_login.csv'}, 'requests': {'url': '/system/login', 'method': 'post', 'data': {...}}, 'validate': {'equals': 2000000, 'assert_str': '$csv{assert_str}'}}"}], "start": 1645671633578, "stop": 1645671633580, "uuid": "ca9de0a7-6b55-492f-9e67-7789f063b0e1", "historyId": "6cb231ebc720696025aad1bdcc8fbe79", "testCaseId": "93a39feb8eb701231e6c069b76eeac98", "fullName": "testcases.test_login.TestLogin#test_login", "labels": [{"name": "feature", "value": "登录测试"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HXPSPQYBEZK8JRT"}, {"name": "thread", "value": "575064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}